apiVersion: v1
kind: Service
metadata:
  name: juice-shop-service
  namespace: juice-shop
  labels:
    app: juice-shop
spec:
  selector:
    app: juice-shop
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP